NDefines.NMilitary.PLAN_SPREAD_ATTACK_WEIGHT = 9
NDefines.NAI.RESERVE_TO_COMMITTED_BALANCE = 0.3
NDefines.NAI.ORG_UNIT_WEAK = 0.3
NDefines.NAI.ORG_UNIT_NORMAL = 0.6
NDefines.NAI.STR_UNIT_WEAK = 0.35
NDefines.NAI.STR_UNIT_NORMAL = 0.65
